### PR TITLE
set up CI

### PR DESCRIPTION
**Pull request by dagurtomas**

### CODE REVIEW

**Review by awodey — APPROVED** [review]
not sure what this is - but whatever ...

**Comment by dagurtomas** [comment]
This builds the project after every commit. You get a green tick if it succeeds (sorries allowed, but no errors). This makes sure you don't merge any contributions that make breaking changes

**Comment by sinhp** [comment]
Very useful @dagurtomas. Thanks for doing it!

**Comment by sinhp** [comment]
Can we have a linter on this too? or does that make too much work?

**Comment by dagurtomas** [comment]
There is just a basic style linter, I have no idea how to add more. It might just be a question of copying a few lines from the corresponding files in mathlib.

**Comment by sinhp** [comment]
I think it's good enough for now.

**Pull request merged**
