### PR TITLE
feat: characterize forget ⊣ star (co)unit

### PR DESCRIPTION
**Pull request by Vtec234**

### CODE REVIEW

**Comment by sinhp** [comment]
Sorry for slow reply. I was working on this file locally, and had to change a lot of things before coming to your PR. Most of your changes have already been implemented in mathlib. In particular, the unit and count of the adjunction exists as the unit and count of the free algebra construction. 

But mainly, we have noticed that there are duplicate things in mathlib and I had to change some things in the file before merging your changes. See the implementation notes of the file: The definitions `Over.pullback` and `mapPullbackAdj`.
Later, `Over.baseChange` and `Over.mapAdjunction` were added which are duplicates, but the latter have additional `simp` lemmas, namely `unit_app` and `counit_app` which makes proving things with `simp` easier.

I expect that in the end we do not need any of the lemmas in the namespace `Over.forgetAdjStar` since they should be obtained automatically by adding certain `simp` attributes to `Over.forgetAdjStar` in mathlib. I am working on this.

**Comment by Vtec234** [comment]
> expect that in the end we do not need any of the lemmas in the namespace `Over.forgetAdjStar` since they should be obtained automatically by adding certain simp attributes to Over.forgetAdjStar in mathlib

Since `forgetAdjStar` is not defined directly but rather in terms of `coalgebraEquivOver` composed with another adjunction, will the auto-generated `@[simps]` be the ones you want, i.e., will they explicitly simplify the counit to `prod.snd`? When I tried it, it seemed to simplify to a bunch of abstract nonsense rather than `prod.snd`.

More generally, the approach that the category theory library takes of putting `@[simps]` on everything worries me a little bit because it leads to `simp` calls that unfold through several layers of abstraction. For faster proofs, it is better to have lemmas that directly simplify higher-level objects.

**Comment by sinhp** [comment]
They do. See for instance `CategoryTheory.Over.forgetAdjStar.unit_app_eq`.

**Comment by sinhp** [comment]
It seems this approach is the standard approach that mathlib has taken so far; I have seen many other examples where more abstract definition involving adjunctions simplify. See for instance 

```
CategoryTheory.Over.mapAdjunction_unit_app.{v, u} {C : Type u} [Category.{v, u} C] [HasPullbacks C] {X Y : C}
  (f : X ⟶ Y) : ∀ (X_1 : Over X), (mapAdjunction f).unit.app X_1 = homMk (pullback.lift (𝟙 X_1.left) X_1.hom ⋯) ⋯
```

**Pull request merged**
